name: Run Jazz Islam World Test

on:
  schedule:
    - cron: '0 8,12,16 * * *'  # Runs at 8 AM, 12 PM, and 4 PM UTC
  workflow_dispatch:

jobs:
  run-selenide-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '22'


      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run Selenide Test
        run: mvn test -Dtest=com.jazzservices.demo.JazzIslamWorldTest
        shell: bash

      - name: Notify Status
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "Jazz Islam World is Working"
          else
            echo "Jazz Islam World is not Working"
          fi


    


