name: Run Selenide Scripts

on:
  schedule:
    - cron: '0 8,12,16 * * *'  # Runs at 8 AM, 12 PM, and 4 PM UTC
      workflow_dispatch:

jobs:
  run-selenide:
    JazzIslamWorldTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run Selenide Script
        run: |
          # Run your Selenide script
          java -jar path/to/YourSelenideScript.jar

      - name: Notify status
        run: |
          # Check status and send notification
          if [ $? -eq 0 ]; then
            echo "Service is working"
            # You can send a notification here, for example, using curl to post to a webhook
          else
            echo "Service is down"
            # Send a notification about failure
          fi